
# Author/Blogger
author: true
name: 'Jony Bepary'
familyname: 'Bepary'
NickName: 'Jhon :)'
webtitle: 'Code With Jhon'
bio: 'Student, Computer Programmer And a Scented Soul'
about: true
aboutyou: "Jony Bepary is a Bangladeshi Computer Scientist. He runs an Educational youtube channel to teach computer programming, mathematics, and Other related stuff."
portraits: '/assets/madara.svg' # your portraits image file path for website


# Author information for SEO
honorificPrefix: "MD."
name: "Jony Bepary"
image: "/assets/JHON.jpg"       # your portraits image file path for seo
familyName: "Bepary"
honorificSuffix: "King"
disambiguatingDescription: "Jony Bepary is a Bangladeshi Computer Scientist. He runs an Educational youtube channel to teach computer programming, mathematics, and Other related stuff."
birthPlace: "Nawdoba, Zanjira, Shariatpur"
birthDate: "1997.10.25"
height: "72 inches"
gender: "male"
nationality: "Bangladeshi"
jobTitle: "Technical support of Software"
knowsAbout: ["C", "Python", "Algorithm", "Web", "Full Stack", ]
knowsLanguage: ["Bangla, English"]
